version: "3.8"
services:
  proxy:
    depends_on:
      - client
      - api
    restart: always
    build:
      context: ./proxy
    ports:
      - "3050:80"
  client:
    stdin_open: true
    build:
      context: ./services/client
    volumes:
      - ./services/client:/app
  api:
    build: ./services/server
    volumes:
      - ./services/server:/home/parkyes90/app
    depends_on:
      - redis
  redis:
    image: redis:6.2.6