name: migrations
on:
  push:
    branches:
      - master
    paths:
      - 'services/server/migrations/*'
jobs:
  slackNotifications:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
      - name: echo
        run: echo ${{ steps.changes.outputs.all }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_TEST_WEB_HOOK }}
          SLACK_USERNAME: RailsMigrationBot
          SLACK_TITLE: Message
          SLACK_MESSAGE: 'Rails Migration Changed. 변경점은 해당 커밋을 참고해주세요.'
