name: migrations
on:
  pull_request:
    types:
      - opened
    paths:
      - 'services/server/migrations/*'
jobs:
  slackNotifications:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          git fetch origin master
          echo "::set-output name=all::$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }})"
      - name: echo
        run: echo ${{ steps.changes.outputs.all }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_TEST_WEB_HOOK }}
          SLACK_USERNAME: RailsMigrationBot
          SLACK_TITLE: Message
          SLACK_MESSAGE: 'Rails Migration Changed. ${{ steps.changes.outputs.all }}'
